<?php

namespace App\Listeners;

use App\Events\LogEventAction;
use App\Models\EventLog;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;

class ModelActionListener
{
    /**
     * Create the event listener.
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     */
    public function handle(LogEventAction $event): void
    {
        $eventData = $event->event;
        $subjectData = $event->subject;
        $descriptionData = $event->description;

        if (auth()->user()) {
            $userId = auth()->user()->id;
            $username = auth()->user()->username;
        } else {
            $userId = 0;
            $username = "Generated by Faker";
        }

        EventLog::create([
            'user_username' => $username,
            'user_id' => $userId,
            'event' => $eventData,
            'subject_type' => get_class($subjectData),
            'subject_id' => $subjectData->id,
            'description' => $descriptionData,
        ]);
    }
}
